### ISSUE TITLE
Host filtering with qp-fastp-minimap2 is done serially

### ISSUE THREAD

**Issue by wasade** [qiita-spots/qp-fastp-minimap2#3]
Samples are processed serially rather than distributed in parallel on execution with this plugin 

cc @cameronmartino @jdereus

**Comment by antgonza** [comment]
This is actually intended or in other words: we haven't move to parallel processing to minimize the number of running jobs in the queue. Also, to consider for decision: this step is actually not that slow (compared to others) and have been hesitant to move so we don't process with job arrays and even clutter more the queues (with 100s of jobs) per processing.

Anyway, at this stage is quite easy to move to parallel processing (via job arrays) but not sure if really worth it ... thoughts?
